### ISSUE TITLE
Add -I${PREFIX}/include to CPPFLAGS

### ISSUE THREAD

**Issue by isuruf** [AnacondaRecipes/aggregate#109]
Some autoconf macros like `AC_EGREP_CPP` fail when `-I${PREFIX}/include` is not added to CPPFLAGS. In conda-forge toolchain package we add `-I${PREFIX}/include` to only CPPFLAGS and the conda compilers add it to CFLAGS and CXXFLAGS because some packages don't look at CPPFLAGS, but in this case, some packages only look at CPPFLAGS. I propose we add `-I` to all 3 of them. Let me know what you think and I can come up with a PR.

**Comment by jjhelmus** [comment]
Adding `-I${PREFIX}/include` to all three variables seems reasonable to me.
