### ISSUE TITLE
mongo-tools

### ISSUE THREAD

**Issue by sodre** [AnacondaRecipes/aggregate#111]
@nehaljwani, would it be possible  to package the mongodb tools with the mongo package? The tools include the commands to backup and restore from a running database.

I am happy to issue a PR if mongodb-feedstock is going to be moved to conda-forge.

**Comment by nehaljwani** [comment]
Are you referring to these? https://github.com/mongodb/mongo-tools

If so, I had thought about that, but didn't include them in the existing mongodb recipe for two reasons:

1. It's a bunch of tools written in go. This recipe is all C++, didn't want to mix two compilers
2. Users installing mongo-tools might not necessarily want the mongo/mongos/mongod/mongoperf binaries.

**Comment by nehaljwani** [comment]
I'd be more open to a recipe at conda-forge for mongo-tools which we would then fork here and put in defaults.

**Comment by sodre** [comment]
I'll get started on the recipe!

**Comment by sodre** [comment]
@nehaljwani, the mongo-tools recipe was added to conda-forge. Let me know if you would like to be added as a recipe-maintainer and or any additional help to close this request.

**Comment by nehaljwani** [comment]
@sodre Yes, you can add me there. I have [forked](https://github.com/AnacondaRecipes/mongo-tools-feedstock) the recipe. As soon as you get the pending PR from the cf bot merged, holler me here and I'll build it and put it in defaults and then close this issue.

**Comment by sodre** [comment]
@nehaljwani, would it be okay to make the 3.6.9 series available in defaults as well? I will follow on with the 4.0.x series immediately after and add you as a maintainer as well.

**Comment by sodre** [comment]
@nehaljwani, 3.6.9 is being built now on conda-forge with mongoreplay. Please feel free to merge it to defaults when you are ready.

I'll follow with the 4.0.x series after that is done.

**Comment by nehaljwani** [comment]
@sodre 3.6.9 is now available on defaults.

**Comment by nehaljwani** [comment]
Closing, as 4.0.4 is also available in defaults now.
