### ISSUE TITLE
Pandas 0.24.0

### ISSUE THREAD

**Issue by TomAugspurger** [AnacondaRecipes/aggregate#118]
Releasing pandas 0.24.0 today.

The recipe changed slightly, since we've dropped support for NumPy 1.11; we now require NumPy >= 1.12.

See the changes in https://github.com/conda-forge/pandas-feedstock/pull/59/files#diff-e178b687b10a71a3348107ae3154e44c, specifically

```
    - numpy 1.14.*  # [py==37]
    - numpy 1.12.*  # [py!=37]
```

in the host section.

**Comment by nehaljwani** [comment]
Closing, as 0.24.0 is available in defaults now.
