### ISSUE TITLE
Pandas 0.24.2

### ISSUE THREAD

**Issue by jorisvandenbossche** [AnacondaRecipes/aggregate#131]
As a heads up, pandas 0.24.2 was released yesterday.

There were no changes in the build system / recipe (https://github.com/conda-forge/pandas-feedstock/pull/61/)

**Comment by jjhelmus** [comment]
@jorisvandenbossche Thanks for the ping.  Packages for 0.24.2 are available in `defaults` for all supported platforms and Python versions.

**Comment by jorisvandenbossche** [comment]
Thanks a lot!
