### ISSUE TITLE
License file for this repo

### ISSUE THREAD

**Issue by jakirkham** [AnacondaRecipes/aggregate#139]
Am not seeing a license file for this repo. Does it have one and I'm just missing it? If not, could one please be added?

**Comment by isuruf** [comment]
https://github.com/AnacondaRecipes/aggregate/issues/39

**Comment by jakirkham** [comment]
Unfortunately that is not good enough for my use case. Could we please add a license file? Thanks.

**Comment by jakirkham** [comment]
Friendly nudge :wink:
