### ISSUE TITLE
CDT for libnl

### ISSUE THREAD

**Issue by jakirkham** [AnacondaRecipes/aggregate#142]
Would be great to have a CDT for `libnl`.

**Comment by nehaljwani** [comment]
Isn't this good enough? https://github.com/conda-forge/libnl-feedstock

**Comment by jakirkham** [comment]
Unfortunately not. We require other CDTs for `librdmacm` ( https://github.com/AnacondaRecipes/aggregate/issues/141 ) and `libibverbs` ( https://github.com/AnacondaRecipes/aggregate/issues/143 ), which link against the system copy of `libnl`.

**Comment by jakirkham** [comment]
Handling in conda-forge with PR ( https://github.com/conda-forge/staged-recipes/pull/8560 ).

**Comment by jakirkham** [comment]
Handled with PR ( https://github.com/conda-forge/staged-recipes/pull/8560 ) and PR ( https://github.com/conda-forge/staged-recipes/pull/8633 ).
