### ISSUE TITLE
Add Scapy

### ISSUE THREAD

**Issue by gpotter2** [AnacondaRecipes/aggregate#161]
Hi,
It would be cool to get [scapy](https://github.com/secdev/scapy) in defaults. It's a quite popular project

We're releasing a new version (2.4.3), and the currently available user-custom feedstocks are all out of date :/

Here's the conda-forge recipe:
https://github.com/conda-forge/scapy-feedstock

Thanks !

**Comment by gpotter2** [comment]
Hello @jjhelmus & sorry for the ping.

It would be awesome if you could please have a look at this. We wanted to have that ready for the release & BlackHat.

Thanks again !

**Comment by msarahan** [comment]
Hi @gpotter2, we don't generally build pre-release packages (Conda-forge generally doesn't either).  When 2.4.3 is officially released, or at least tagged, can you let us know?

**Comment by gpotter2** [comment]
Thanks for the reply. Will do

(It was an exceptional case that it got into conda-forge, as the previous release had an installation issue)

**Comment by gpotter2** [comment]
Hello @msarahan,
2.4.3 was released yesterday. Should be good to go

Thanks !

**Comment by msarahan** [comment]
uploading now.  Thanks @gpotter2

**Comment by gpotter2** [comment]
Thanks ! :+1:
