### ISSUE TITLE
Windows Build of Redis?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [AnacondaRecipes/aggregate#17]
I see a redis feedstock has been added, it doesn't support Windows.

Windows would be nice :-)

Here are some options:

There is the MS project:

https://github.com/MicrosoftArchive/redis

but:

* it doesn't look like it's been touched in a while (a year)
* the build instructions require point and click in VS -- annoying! though there is probably a way to script that if someone knows about Windows building...

The good part is that it is stand-alone, so doesn't have to use any particular run time environment...

Though maybe just copying binaries is easier, there are some online here:

https://github.com/dmajkic/redis/downloads

**Comment by nehaljwani** [comment]
```
(root) [nwani@bremen main]$ conda search --spec redis --platform win-64
Fetching package metadata ...........
redis                        3.2.100              h81e342f_0  defaults
