### ISSUE TITLE
Add `run_exports` to `cudnn`

### ISSUE THREAD

**Issue by jakirkham** [AnacondaRecipes/aggregate#173]
It would be good to add `run_exports` to the `cudnn` package. This would allow downstream packages to rely on `cudnn` to express its own compatibility without having to use `pin_compatible` on their own.

**Comment by jakirkham** [comment]
Copying this from the developer documentation (link below):

> **cuDNN API Compatibility**
>
> Beginning in cuDNN 7, the binary compatibility of patch and minor releases is maintained as follows:
>
> * Any patch release x.y.z is forward- or backward-compatible with applications built against another cuDNN patch release x.y.w (i.e., of the same major and minor version number, but having w!=z)
> * cuDNN minor releases beginning with cuDNN 7 are binary backward-compatible with applications built against the same or earlier patch release (i.e., an app built against cuDNN 7.x is binary compatible with cuDNN library 7.y, where y>=x)
> * Applications compiled with a cuDNN version 7.y are not guaranteed to work with 7.x release when y > x.

ref: https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#programming-model

**Comment by jakirkham** [comment]
FWIW we have added a global pinning of `cudnn` in conda-forge to address this issue for now. ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/310 )

**Comment by jjhelmus** [comment]
I agree, the `cudnn` package should have a `run_exports`.  The package is due for an update to version 7.6.4. I'll add a note to myself to add run_exports when the package is updated.

**Comment by jakirkham** [comment]
That would be great. Thanks Jonathan! 😄

**Comment by jjhelmus** [comment]
cudnn 7.6.4 packages are now available in `defaults` for win-64 and linux-64 and include a `run_export` for `cudnn >=7.6,<8.0a0`.

**Comment by jakirkham** [comment]
cc @mike-wendt @raydouglass @kkraus14 (for awareness)
