### ISSUE TITLE
Add enaml recipe

### ISSUE THREAD

**Issue by MatthieuDartiailh** [AnacondaRecipes/aggregate#21]
A new version of enaml supporting Python 3 and Qt5 has been published and is now available on conda-forge. Could please pull it in aggregate ?

**Comment by MatthieuDartiailh** [comment]
ping

**Comment by MatthieuDartiailh** [comment]
Version 0.10.2 has just been released and is on conda-forge. It fixes a number of bugs from the previous version. Could it be added to aggregate ?

**Comment by MatthieuDartiailh** [comment]
Can I do anything to help this happen ?

**Comment by nehaljwani** [comment]
@MatthieuDartiailh enaml 0.10.2 was added on Feb 27, 2018
