### ISSUE TITLE
Missing libquadmath.so

### ISSUE THREAD

**Issue by chenghlee** [AnacondaRecipes/aggregate#32]
`readelf -d $CONDA_PREFIX/lib/libgfortran.so.4.0.0` (from the `libgfortran-ng-7.2.0-h9f7466a_2` package) shows one of its needed shared libraries is `libquadmath.so.0`. However, none of the packages I can find in the "defaults" channel provides this dynamic library.

When building a simple "hello world" FORTRAN application, I get the following error:
```
$ $CONDA_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gfortran hello-world.f90 -o hello-world
$CONDA_PREFIX/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lquadmath
```

The contents of `hello-world.f90`:
```
program HelloWorld
print*,"Hello world"
end program
```

**Comment by nehaljwani** [comment]
@chenghlee Try installing the libgcc-ng conda package. You will find libquadmath.so there.

cc @mingwandroid

**Comment by msarahan** [comment]
If you're using conda-build, the dependencies should be getting added automatically for you with run_exports.  If you're using the compilers on your own without conda-build, then you're on your own.  We'd be interested in fixing things if you are using conda-build but not getting the appropriate deps.

**Comment by chenghlee** [comment]
Installing `libgcc-ng` does indeed fix this issue. However, the `libgfortran-ng` package should have a dependency on `libgcc-ng` to ensure `libquadmath` is always installed when using the `libgfortran-ng` conda package.

**Comment by msarahan** [comment]
fixed in https://github.com/AnacondaRecipes/aggregate/pull/14

new compiler packages are coming soon
