### ISSUE TITLE
Update dask and distributed libraries

### ISSUE THREAD

**Issue by mrocklin** [AnacondaRecipes/aggregate#35]
These have been updated on conda-forge.  It would be nice to have them in defaults as well (this is now blocking some docker work if I want to continue using the defaults channel).

**Comment by mrocklin** [comment]
Updated versions of `dask-core=0.17.1`, `distributed=1.21.1`, and `dask=0.17.1` now on conda-forge

**Comment by jjhelmus** [comment]
Thanks for the heads up @mrocklin, I'll start build of these immediately.

**Comment by jjhelmus** [comment]
`dask-core=0.17.1`, `distributed=1.21.1`, and `dask=0.17.1` are now available on `defaults`.

**Comment by mrocklin** [comment]
Huzzah!
