### ISSUE TITLE
Add doit?

### ISSUE THREAD

**Issue by ceball** [AnacondaRecipes/aggregate#37]
Would it be possible to add doit (http://pydoit.org/)?

doit is available on the conda-forge channel (https://anaconda.org/conda-forge/doit; https://github.com/conda-forge/doit-feedstock).

**Comment by ceball** [comment]
Ideally, would be good to get 0.31.1 (the latest - which is currently only a [PR](https://github.com/conda-forge/doit-feedstock/pull/2) on c-f).

However, I think it might also be necessary to have 0.29.0, because that was the last version to support python 2 (2.7).

**Comment by jjhelmus** [comment]
This would require adding an os-x [`macfsevents`](https://github.com/conda-forge/macfsevents-feedstock) package and linux [`pyinotify`](https://github.com/conda-forge/pyinotify-feedstock) packages as well.  Both have conda-forge recipes.

**Comment by jjhelmus** [comment]
doit 0.31.1 and 0.29.0 are now available in `defaults`
