### ISSUE TITLE
Updating Tensorflow/Tensorboard

### ISSUE THREAD

**Issue by jakirkham** [AnacondaRecipes/aggregate#44]
Looks like Tensorflow/Tensorboard 1.4.1 (in its various incarnations) is included here. However since then 1.5.1, 1.6.0, and 1.7.0 have been released. Also a 1.8.0 RC0 is already out. Would be great to get this updated. Admittedly that may be a fair amount of work.

Side note: Tensorflow 1.8.0 will require CUDA 8.0+ and cuDNN 6.0+.

**Comment by jjhelmus** [comment]
Updating Tensorflow, including GPU builds is on the current sprint plan so expect to see some updating to these packages in the near future.  Tensorflow 1.5.0 and 1.6.0 are available for linux-64, although the gpu version is still at 1.4.1.

**Comment by jjhelmus** [comment]
Tensorflow 1.5.0, 1.6.0 and 1.7.0 are available in both CPU (tensorflow) and GPU (tensorflow-gpu) form for linux-64 in `defaults`.  The GPU builds support either CUDA 8 or CUDA 9, selection can be done by specifying the version of the cudatoolkit package.

**Comment by jakirkham** [comment]
That's great news! Thanks Jonathan. Let's close this out. :)
