### ISSUE TITLE
Adding -headerpad_max_install_names to LDFLAGS on macOS

### ISSUE THREAD

**Issue by jakirkham** [AnacondaRecipes/aggregate#45]
Wasn't able to tell if this was already happening. So this could be a non-issue.

Thought it would be nice if the macOS compiler activation scripts added `-headerpad_max_install_names` to `LDFLAGS` on macOS to effectively get the longest prefix allowable on macOS to start with. We currently use this in `conda-forge`'s `toolchain` package. Thoughts on using it here as well?

**Comment by msarahan** [comment]
please refer to the Dropbox Paper document for the conda-forge compiler meeting on Nov. 11 last year.  We've had this flag in place longer than it has been in toolchain.

 https://paper.dropbox.com/doc/2017-11-16-2018-02-20-meeting-notes-compiler-1lYaDIP93JRzzQZBlicxg

**Comment by jjhelmus** [comment]
This flag gets set in the llvm-compilers feedstock, see the [conda_build_config.macOS_10.9.yaml](https://github.com/AnacondaRecipes/aggregate/blob/master/llvm-compilers-feedstock/recipe/conda_build_config.macOS_10.9.yaml)

**Comment by msarahan** [comment]
@jjhelmus, I am pretty sure that is vestigial. These need to be set in an activation script package, which we split off from the actual compiler packages.

I think the right link is https://github.com/AnacondaRecipes/aggregate/blob/master/clang/build.sh

This is in the Dropbox did I linked above.

**Comment by jakirkham** [comment]
So I think this is highlighting the same confusion that caused me to raise this issue. Where do we look for how the compiler works? Ideally one doesn't want to rely on meetings docs from ~6mos ago (who knows if that is current), looking at the code for this sort of stuff is far more preferable, but it is not obvious where to look. Does it make sense for the compilers to live in their own repo so this is easier to see?

**Comment by msarahan** [comment]
https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#customizing-the-compilers

We need the similar docs for Linux and win.

Compilers in their own repo is reasonable. Having them as plain folders in
the aggregate repo does make them hard to find.

I'd say though that the clang docs really should be easily findable, and
I'd like to understand what you looked for so that maybe we can add words
to the docs that would help Google find them.
