### ISSUE TITLE
Add PDAL feedstock (and dependencies) to Anaconda

### ISSUE THREAD

**Issue by chambbj** [AnacondaRecipes/aggregate#67]
The PDAL package (along with it's dependencies) are available as conda-forge feedstocks. It would be fabulous if we could get these added to Anaconda as well. I'm not sure if you would like an issue for each individual package, or if a list will do.

- [ ] https://github.com/conda-forge/pdal-feedstock
- [ ] https://github.com/conda-forge/hexer-feedstock
- [ ] https://github.com/conda-forge/laz-perf-feedstock/
- [ ] https://github.com/conda-forge/nitro-feedstock/
- [ ] https://github.com/conda-forge/laszip-feedstock/
- [ ] https://github.com/conda-forge/pcl-feedstock/
- [ ] https://github.com/conda-forge/python-pdal-feedstock/
- [ ] https://github.com/conda-forge/flann-feedstock/

**Comment by chambbj** [comment]
@msarahan I believe you helped with a few of these when I first submitted to conda-forge/staged-recipes. This ticket hasn't really attracted much discussion over the past month. :wink: I know not every conda-forge recipe can make the cut, but I'm curious what the chances are that we may be able to move forward with this.

**Comment by chambbj** [comment]
@mingwandroid @jjhelmus Looking for a little feedback here. Curious about the prospects of adding PDAL and associated feedstocks as described. Thanks!

**Comment by msarahan** [comment]
That's a lot of dependencies. To give you some perspective, we are currently holding steady at about 200 packages that are out of date. We update about 100 recipes per 2 week sprint on average (more if it's a focus, less when other things are more urgent). We are working on automation practices that will extend our capabilities to cope with more packages, but until then, I do not think we can take on PDAL.

**Comment by chambbj** [comment]
Alright. Thanks for getting back to me. I wasn't sure if I should hold out
hope or not.

**Comment by msarahan** [comment]
Please check in with us again in a few months. If you see any blog post from us on automation, that would be a sign to check in.
