### ISSUE TITLE
Update basemap to 1.1.0

### ISSUE THREAD

**Issue by mattvw** [AnacondaRecipes/aggregate#74]
Can you please update basemap in Anaconda3 to the latest version already available in conda-forge (1.1.0)?

It still shows 1.0.7 as the latest version of basemap via normal conda, which requires an older version of numpy (1.13.3). So, trying to install basemap with Anaconda3 5.2.0 wants to REMOVE latest anaconda3 package (5.2.0) completely, since 5.2.0 requires numpy=1.14.3.

I would greatly appreciate basemap being updated to the latest version available in conda-forge (1.1.0) as soon as possible!

Thank you!

**Comment by csoja** [comment]
closing - as the latest version of basemap on repo.anaconda.com now is 1.2.0.
