### ISSUE TITLE
Update Dask-ML to 0.9.0

### ISSUE THREAD

**Issue by TomAugspurger** [AnacondaRecipes/aggregate#81]
conda-forge PR at https://github.com/conda-forge/dask-ml-feedstock/pull/11

This had some significant changes to the recipe, since we moved from Cython to numba. The conda-forge package is now a noarch package.

**Comment by jjhelmus** [comment]
Thanks for the heads up on the new build requirements @TomAugspurger 
dask-ml 0.9.0 is now available in `defaults`.

**Comment by TomAugspurger** [comment]
Thanks!
